import SwiftUI

struct PauseView: View {
    @EnvironmentObject var breakManager: BreakManager
    
    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()
            
            VStack(spacing: 20) {
                // Design was generated by Claude Opus 5 (everything in VStack)
                Text("Take a Break!")
                    .font(.system(size: 48, weight: .bold))
                    .foregroundColor(.white)
                
                Button("Resume Work") {
                    WindowManager.shared.closeWindow()
                    breakManager.startTimer()
                }
                .buttonStyle(.borderedProminent)
                .controlSize(.large)
            }
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

